In [1]:
import numpy as np

In [2]:
sales_data = np.array([
    [200, 220, 250, 270],  # Product A
    [150, 160, 170, 180],  # Product B
    [300, 310, 320, 330]   # Product C
])

In [12]:
total_sales = np.sum(sales_data, axis=1)  # axis=1 sums across columns (quarters)
total_sales

array([ 940,  660, 1260])

In [13]:
average_sales_per_quarter = np.mean(sales_data, axis=0)  # axis=0 averages across rows (products)
average_sales_per_quarter

array([216.66666667, 230.        , 246.66666667, 260.        ])

In [11]:
max_sales_each_quarter = np.max(sales_data, axis=0)
max_sales_each_quarter

array([300, 310, 320, 330])

In [3]:
random_data = np.random.rand(4, 5)  # 4x5 array of random numbers

In [14]:
mean_random_data = np.mean(random_data)

In [4]:
revenue_data = np.array([10.5, 12.3, 14.8, 11.2, 13.9])

In [17]:
std_revenue = np.std(revenue_data)
std_revenue

1.6107141273360712

In [18]:
normalized_revenue = (revenue_data - np.mean(revenue_data)) / np.std(revenue_data)
normalized_revenue

array([-1.26651897, -0.14900223,  1.40310435, -0.83192913,  0.84434598])

In [5]:
stock_prices = np.array([
    [101, 103, 107, 105, 102, 108, 110],
    [98, 97, 95, 96, 99, 101, 100],
    [150, 152, 153, 154, 151, 150, 149],
    [75, 74, 73, 76, 78, 79, 80],
    [120, 121, 123, 125, 124, 122, 126]
])

In [19]:
daily_returns = np.diff(stock_prices, axis=1) / stock_prices[:, :-1] * 100
daily_returns

array([[ 1.98019802,  3.88349515, -1.86915888, -2.85714286,  5.88235294,
         1.85185185],
       [-1.02040816, -2.06185567,  1.05263158,  3.125     ,  2.02020202,
        -0.99009901],
       [ 1.33333333,  0.65789474,  0.65359477, -1.94805195, -0.66225166,
        -0.66666667],
       [-1.33333333, -1.35135135,  4.10958904,  2.63157895,  1.28205128,
         1.26582278],
       [ 0.83333333,  1.65289256,  1.62601626, -0.8       , -1.61290323,
         3.27868852]])

In [20]:
highest_price_day = np.argmax(stock_prices, axis=1)
highest_price_day

array([6, 5, 3, 6, 6])

In [21]:
transposed_stock_prices = np.transpose(stock_prices)
transposed_stock_prices

array([[101,  98, 150,  75, 120],
       [103,  97, 152,  74, 121],
       [107,  95, 153,  73, 123],
       [105,  96, 154,  76, 125],
       [102,  99, 151,  78, 124],
       [108, 101, 150,  79, 122],
       [110, 100, 149,  80, 126]])